SET SCHEMA public;

DROP TABLE BOOK;
DROP TABLE PARAGRAPH;

CREATE TABLE public.BOOK (
  BOOKID INT          IDENTITY,
  NAME   VARCHAR(200) NOT NULL,
  AUTHOR VARCHAR(200) NOT NULL/*,
  CONSTRAINT pk_book PRIMARY KEY (bookid)*/
);

CREATE TABLE public.PARAGRAPH (
  PARAGRAPHID INT          IDENTITY,
  BOOKID      INT          NOT NULL,
  NUMBER      INT          NOT NULL,
  TEXT        VARCHAR(255) NOT NULL,
/*  CONSTRAINT pk_paragraph PRIMARY KEY (PARAGRAPHID),*/
  CONSTRAINT fk_product_1 FOREIGN KEY (BOOKID)
  REFERENCES public.BOOK (bookid)
);